#progression imported from ToneGym!#
CHORD_PROGRESSIONS = {
    "Pachelbel's Canon": ["I", "V", "vi", "iii", "IV", "I", "IV", "V"],
    "50s Progression": ["I", "vi", "IV", "V"],
    "Cadence Progression": ["ii", "V", "I"],
    "Happy Progression": ["I", "I", "IV", "V"],
    "Sad 1 Progression": ["vi", "IV", "I", "V"],
    "Sad 2 Progression": ["vi", "iii", "V", "IV"],
    "Sad 3 Progression": ["i", "v", "bVII", "iv"],
    "Sadder Progression": ["i", "v", "bVII", "IV"],
    "Uplifting Progression": ["vi", "V", "IV", "V"],
    "Andalusian Cadence Progression": ["i", "bVII", "bVI", "V"],
    "Storyteller Progression": ["I", "IV", "vi", "V"],
    "Bass Player Progression": ["I", "ii", "I", "IV"],
    "Journey Progression": ["IV", "I", "V", "V"],
    "Secondary Dominants Progression": ["IV", "V", "III", "vi"],
    "Circle Progression": ["vi", "ii", "V", "I"],
    "Minor Change Progression": ["IV", "iv", "I", "I"],
    "La Bamba Progression": ["I", "IV", "V", "IV"],
    "Epic Progression": ["I", "bVI", "V", "V"],
    "Blues 12-Bar Progression": ["I", "I", "I", "I", "IV", "IV", "I", "I", "V", "IV", "I", "V"],
    "Blues 12-Bar V2 Progression": ["I", "IV", "I", "I", "IV", "IV", "I", "I", "V", "IV", "I", "V"],
    "Pop 1 Progression": ["I", "vi", "iii", "II"],
    "Pop 2 Progression": ["I", "V", "vi", "IV"],
    "Rock 1 Progression": ["I", "IV", "I", "V+"],
    "Rock 2 Progression": ["i", "bVI", "iv", "iv"],
    "Rock 3 Progression": ["IV", "V", "vi", "I"],
    "Rock 4 Progression": ["I", "I", "bVII", "IV"],
    "Rock 5 Progression": ["I", "V", "ii", "IV"],
    "Jazz 1 Progression": ["ii", "V", "I", "I"],
    "Jazz 2 Progression": ["I", "vi", "ii", "V"],
    "Jazz 3 Progression": ["I", "bVII", "vi", "bIII", "ii", "bVI", "V", "bII"],
    "Jazz 4 Progression": ["iii", "ii", "V", "I"],
    "Jazz 5 Progression": ["I", "V", "IV", "iv"],
    "Trap Progression": ["i", "bVI", "i", "v"],
}


